services:
  app:
    image: iseh/compara:latest
    volumes:
      - ./app:/app
    ports:
      - "8183:8183"
    secrets:
      - mongo_uri
      - secret_jwt
      - turnstile_secret_key
      - turnstile_site_key
    environment:
      - MONGO_URI=/run/secrets/mongo_uri
      - SECRET_JWT=/run/secrets/secret_jwt
      - TURNSTILE_SECRET_KEY=/run/secrets/turnstile_secret_key
      - TURNSTILE_SITE_KEY=/run/secrets/turnstile_site_key
    depends_on:
      - db
    networks:
      - group3-network

  db:
    image: mongo:latest
    container_name: compara_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=newUriPwdFordbMongodb
      - MONGO_INITDB_DATABASE=compara_db 
      - MONGO_LOGLEVEL=1
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - group3-network
volumes:
  mongo_data:
    driver: local

networks:
  group3-network:
    driver: bridge

secrets:
  mongo_uri:
    file: ./secrets/mongo_uri.txt
  secret_jwt:
    file: ./secrets/secret_jwt.txt
  turnstile_secret_key:
    file: ./secrets/turnstile_secret_key.txt
  turnstile_site_key:
    file: ./secrets/turnstile_site_key.txt