services:
  app:
    image: iseh/compara:latest # based on fork
    #build:
    #  context: ./app
    #container_name: app
    volumes:
      - ./app:/app
    ports:
      - "8183:8183"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_JWT=${SECRET_JWT}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
    depends_on:
      - db
    networks:
      - group3-network

  db:
    image: mongo:latest
    container_name: compara_db
    restart: always
    # env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
      - MONGO_INITDB_DATABASE=compara_db 
      - MONGO_LOGLEVEL=1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - group3-network
volumes:
  mongo_data:
    driver: local

networks:
  group3-network:
    driver: bridge
