# commenting out stuff for production currently

FROM node:18

#WORKDIR /app

#COPY package.json /app/
#COPY package-lock.json /app/

#RUN npm install

#COPY . /app

#EXPOSE 3000

# for development mode
#CMD ["npm", "run", "dev"]
